### ISSUE TITLE
Typo in the tab config?

### ISSUE THREAD

**Issue by manuelhaussmann** [Phantas0s/mouseless-book-companion#3]
I might be missing something but could it be that the three lines l[38-40](https://github.com/Phantas0s/mouseless-book-companion/blob/037b9ed28929d0cd249be65ee5130cbcbdb7bf37/part_II/05_package_managers/.Xresources#L38) have a typo?

```
URxvt*keysym.Control-Shift-N: perl:tabbedex:new_tab
URxvt*keysym.Control-Shift-K: perl:tabbedex:next_tab
URxvt*keysym.Control-Shift-J: perl:tabbedex:prev_tab
URxvt.keysym.Control-Shift-R: perl:tabbedex:rename_tab
URxvt.keysym.Control-Shift-H: perl:tabbedex:move_tab_left
URxvt.keysym.Control-Shift-L: perl:tabbedex:move_tab_right
```
In the first three lines the `*` should be `.` as in the last three lines if I see it correctly.

**Comment by Phantas0s** [comment]
Hey manuel! Thanks for the feedback. You can actually use both * or ., but it's not very consistent indeed. Thanks for that! :)
